# runtime: python37
# instance_class: B8

# handlers:
# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

# basic_scaling:
#   idle_timeout: 30m
#   max_instances: 10



runtime: python
env: flex
entrypoint: gunicorn -b :$PORT --threads=4 main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

resources:
  cpu: 4
  memory_gb: 20
#   disk_size_gb: 10
